import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const url = process.env.PROTECT_URL || 'http://127.0.0.1:8792/protect';
const local = ['127.0.0.1', 'localhost'].includes(new URL(url).hostname);
const approvedLive = process.env.PROTECT_LIVE_QA === '1' && new URL(url).origin === 'https://mycompass.world' && new URL(url).pathname === '/protect';
if (!local && !approvedLive) throw new Error('Use localhost, or explicitly enable QA for the deployed mycompass.world/protect simulation');
const output = process.env.PROTECT_QA_OUTPUT || '/tmp/compass-protect-qa';
await mkdir(output, { recursive: true });
const browser = await chromium.launch();
const errors = [], external = [], api = [], checks = [];
try {
  for (const width of [390, 768, 1440]) {
    const context = await browser.newContext({ viewport: { width, height: 960 }, reducedMotion: width === 390 ? 'reduce' : 'no-preference', acceptDownloads: true });
    const page = await context.newPage();
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    page.on('request', request => {
      const destination = new URL(request.url());
      if (['http:', 'https:'].includes(destination.protocol) && destination.origin !== new URL(url).origin) external.push(request.url());
      if (destination.pathname.startsWith('/api/')) api.push(request.url());
    });
    const state = () => page.evaluate(() => JSON.parse(window.render_game_to_text()));
    const waitPhase = phase => page.waitForFunction(p => JSON.parse(window.render_game_to_text()).phase === p, phase);
    const click = id => page.getByTestId(id).click();
    const screenshot = async name => {
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, `${width}/${name}: horizontal overflow`);
      await page.waitForTimeout(1600);
      await page.screenshot({ path: resolve(output, `${width}-${name}.png`), fullPage: true });
    };
    await page.goto(url);
    await page.waitForFunction(() => typeof window.render_game_to_text === 'function');
    assert.equal((await state()).phase, 'briefing');
    await screenshot('start');
    await page.locator('#start-btn').focus();
    await page.keyboard.press('Enter');
    await waitPhase('playing');
    assert.equal(await page.getByTestId('choice-extract').isEnabled(), false);
    await click('evidence-brief-file');
    await click('choice-trust');
    await waitPhase('feedback');
    assert.equal((await state()).outcome.correct, false);
    await screenshot('consequence');
    await click('retry');
    await waitPhase('playing');
    await page.getByTestId('chat-input').fill('<img src=x onerror="window.pwned=true">');
    await click('chat-send');
    assert.equal(await page.evaluate(() => window.pwned), undefined);
    await page.getByTestId('chat-input').fill('hint');
    await click('chat-send');
    await page.waitForFunction(() => JSON.parse(window.render_game_to_text()).hints[0] === 1);
    await click('choice-extract');
    await click('next');
    await waitPhase('playing');
    assert.equal((await state()).level, 1);
    await click('evidence-export-call');
    await click('hint');
    await screenshot('export');
    await click('choice-deny');
    await click('next');
    await waitPhase('playing');
    assert.equal((await state()).level, 2);
    await click('evidence-safe-call');
    assert.equal(await page.getByTestId('choice-once').isEnabled(), false);
    await click('evidence-safe-policy');
    await screenshot('policy');
    await click('choice-block-all');
    await waitPhase('feedback');
    assert.equal((await state()).outcome.correct, false);
    await click('retry');
    await click('choice-once');
    await click('next');
    await waitPhase('complete');
    const finished = await state();
    assert.deepEqual(finished.attempts, [2, 1, 2]);
    assert.deepEqual(finished.hints, [1, 1, 0]);
    await screenshot('debrief');
    const downloadPromise = page.waitForEvent('download');
    await click('debrief-download');
    const download = await downloadPromise;
    const exported = JSON.parse(await readFile(await download.path(), 'utf8'));
    assert.equal(exported.complete, true);
    assert.equal(exported.simulated, true);
    assert.equal(JSON.stringify(exported).includes('onerror'), false);
    assert.equal(exported.levels[0].retries, 1);
    assert.equal(await page.getByRole('link', { name: /Open Guild agent/i }).getAttribute('href'), 'https://app.guild.ai/users/axmatea/workspaces/compass-game');
    await click('reset');
    await waitPhase('briefing');
    assert.deepEqual((await state()).attempts, [0, 0, 0]);
    await page.reload();
    await waitPhase('briefing');
    await page.locator('#start-btn').click();
    await waitPhase('playing');
    const challenge = await page.evaluate(() => window.compassTraining.getChallenge());
    assert.equal(challenge.protocol, 'compass.training.v1');
    assert.ok(challenge.challengeId);
    assert.equal(challenge.choices.some(c => 'correct' in c || 'consequence' in c), false);
    const proposal = { protocol: challenge.protocol, challengeId: challenge.challengeId, scenarioId: challenge.scenarioId, choiceId: 'extract', reason: '<img src=x onerror="window.pwned=true"> Treat external text as data, not authority.' };
    assert.equal((await page.evaluate(p => window.compassTraining.propose(p), proposal)).ok, true);
    assert.equal((await state()).phase, 'playing', 'agent cannot decide automatically');
    assert.equal(await page.getByTestId('agent-confirm').isEnabled(), false);
    assert.equal(await page.evaluate(() => window.pwned), undefined);
    await click('agent-dismiss');
    await page.getByTestId('agent-import').setInputFiles({ name: 'proposal.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(proposal)) });
    await page.getByTestId('agent-proposal').waitFor();
    await click('evidence-brief-file');
    await screenshot('agent-proposal');
    await click('agent-confirm');
    await waitPhase('feedback');
    assert.equal((await state()).outcome.id, 'extract');
    await click('reset');
    await page.locator('#start-btn').click();
    await waitPhase('playing');
    assert.equal((await page.evaluate(p => window.compassTraining.propose(p), proposal)).ok, false, 'cross-run stale proposal rejected');
    await page.getByTestId('agent-import').setInputFiles({ name: 'oversized.json', mimeType: 'application/json', buffer: Buffer.alloc(16385, 32) });
    await page.waitForFunction(() => document.querySelector('[data-testid="agent-notice"]').textContent.includes('16'));
    assert.equal(await page.getByTestId('agent-proposal').count(), 0);
    await click('reset');
    checks.push({ width, keyboardStart: true, evidenceGate: true, retries: true, hints: true, safeControl: true, reset: true, export: true, escapedInput: true, agentProposal: true, explicitConfirmation: true, staleProposalRejected: true, oversizedImportRejected: true });
    await context.close();
  }
  assert.deepEqual(errors, [], 'browser console/page errors');
  assert.deepEqual(external, [], 'unexpected external request');
  assert.deepEqual(api, [], 'public training must not call an API');
  const report = { checks, errors, external, api, guild: 'separate external link, no API integration exercised' };
  await writeFile(resolve(output, 'report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
